In [5]:
import torch
from torch._C import ParameterDict
import torch.nn as nn
import torchvision.models as models
import numpy as np
from torch.autograd import Variable
from torchvision import datasets, transforms
import torch.nn.functional as F
import torchvision.utils as vutils
from io import open
import os
from PIL import Image
from torchvision.models import mobilenet_v2
import pretrainedmodels
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

imagepath = "//Users/hilmyveradin/Documents/Documents/Programing-Others/WEB-PeriksaParu.com/static/TB (4).png"
image = Image.open(imagepath).convert("RGB")

transform = transforms.Compose([
    transforms.RandomRotation(10),
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

input = transform(image)
input = input[None]

mnet = mobilenet_v2(pretrained=True)
for param in mnet.parameters():
    param.requires_grad = False

class MyCustomMobileNetV2(nn.Module):
    def __init__(self):
        super().__init__()
        self.mnet = mobilenet_v2(pretrained=True)
        self.mnet.classifier = nn.Sequential(
            nn.Linear(1280, 5),
            nn.Sigmoid()
        )
        
    def forward(self, x):
        return self.mnet(x)


MODEL = MyCustomMobileNetV2()
MODEL.load_state_dict(torch.load("/Users/hilmyveradin/Documents/Documents/Programing-Others/WEB-PeriksaParu.com/test_model/weights_best_with random.pth", map_location=torch.device('cpu')))
MODEL.eval()
output = MODEL(input)
output1 = output.detach().numpy()
result = output1[0,0]

if (output.argmax(1)) == 0:
    print("COVID19")
    result = output1[0,0]*100
elif (output.argmax(1)) == 1:
    print("NORMAL")
    result = output1[0,1]*100
elif (output.argmax(1)) == 2:
    print("PNEUMONIA")
    result = output1[0,2]*100
elif (output.argmax(1)) == 3:
    print("PNEUMONIA")
    result = output1[0,3]*100 
else:
    print("TBC")
    result = output1[0,3]*100
    
print(output)
print("----------------")
print("{0:.2f}".format(result))
print("----------------")
print(output.argmax(1))

TBC
tensor([[0.0996, 0.0568, 0.2386, 0.0489, 0.9997]], grad_fn=<SigmoidBackward>)
----------------
4.89
----------------
tensor([4])


In [60]:
hasil = output.detach().numpy()
hasil[0,4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [59]:
sm = torch.nn.Softmax()
prob = sm(output)

"""if prob[:,0] > prob[:,1] and prob[:,0] > prob[:,2] and prob[:,0] > prob[:,3]:
    print(prob[:,0])
elif prob[:,1] > prob[:,0] and prob[:,1] > prob[:,2] and prob[:,1] > prob[:,3]:
    print(prob[:,0])
elif prob[:,2] > prob[:,0] and prob[:,2] > prob[:,1] and prob[:,2] > prob[:,3]:
    print(prob[:,0])
elif prob[:,3] > prob[:,0] and prob[:,3] > prob[:,1] and prob[:,3] > prob[:,2]:
    print(prob[:,0])
else:
    print("Invalid input!")"""

prob

/Users/hilmyveradin/opt/miniconda3/envs/deep_learning/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  


tensor([[0.4754, 0.1749, 0.1749, 0.1749]], grad_fn=<SoftmaxBackward>)

In [53]:
out = output.detach().numpy()[:,0]

In [4]:
y = out.astype(np.float)

/Users/hilmyveradin/opt/miniconda3/envs/deep_learning/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [97]:
print(y)

[13.994627]
